// <auto-generated />
using System;
using FantasyDomainManager.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FantasyDomainManager.Migrations
{
    [DbContext(typeof(DomainDb))]
    [Migration("20251121221654_ChangeDomainIdToString")]
    partial class ChangeDomainIdToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FantasyDomainManager.Models.Domain", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Income")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IncomeLowerLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IncomeUpperLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Population")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ruler")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpkeepCost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpkeepCostLowerLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpkeepCostUpperLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("FantasyDomainManager.Models.Enterprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DomainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Income")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IncomeLowerLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IncomeUpperLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpkeepCost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpkeepCostLowerLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpkeepCostUpperLimit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.ToTable("Enterprises");
                });

            modelBuilder.Entity("FantasyDomainManager.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Wage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("FantasyDomainManager.Models.Troop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DomainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Wage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.ToTable("Troops");
                });

            modelBuilder.Entity("FantasyDomainManager.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FantasyDomainManager.Models.Enterprise", b =>
                {
                    b.HasOne("FantasyDomainManager.Models.Domain", "Domain")
                        .WithMany("Enterprises")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("FantasyDomainManager.Models.Hero", b =>
                {
                    b.HasOne("FantasyDomainManager.Models.Domain", "Domain")
                        .WithMany("Heroes")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("FantasyDomainManager.Models.Troop", b =>
                {
                    b.HasOne("FantasyDomainManager.Models.Domain", "Domain")
                        .WithMany("Troops")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("FantasyDomainManager.Models.Domain", b =>
                {
                    b.Navigation("Enterprises");

                    b.Navigation("Heroes");

                    b.Navigation("Troops");
                });
#pragma warning restore 612, 618
        }
    }
}
